#pragma once

// GENERATED by tools/bots/train_bots.py - do not edit by hand; run the script.
// The bots' perceptron weights (ADR 046): per bot, per exercise, a threshold
// per skill bucket (the level where the bot is half-way between guessing and
// sure), a slope per exercise, one lapse rate. Sources for the teacher the
// weights were trained on: docs/research/2026-09-bot-hearing.md.

namespace BotWeights
{
    constexpr int maxBuckets = 7;
    constexpr int bucketsOf[9] { 7, 3, 5, 5, 4, 4, 4, 4, 7 };

    struct Weights
    {
        float threshold[9][7];
        float slope[9];
        float lapse;
    };

    // hound, cat, viper, owl, bat, elephant (BotListener::Bot order)
    constexpr Weights weights[6] {
        { // hound
            {
                { 3.82f, 5.56f, 6.36f, 6.98f, 7.18f, 7.57f, 7.60f },   // band
                { 6.71f, 7.26f, 7.90f, 0.00f, 0.00f, 0.00f, 0.00f },   // comp
                { 5.12f, 5.14f, 5.36f, 5.23f, 5.42f, 0.00f, 0.00f },   // verb
                { 3.69f, 4.40f, 4.72f, 4.18f, 3.58f, 0.00f, 0.00f },   // pan
                { 7.39f, 7.27f, 7.28f, 7.18f, 0.00f, 0.00f, 0.00f },   // delay
                { 6.55f, 7.68f, 6.80f, 7.33f, 0.00f, 0.00f, 0.00f },   // dist
                { 4.51f, 4.87f, 4.82f, 4.93f, 0.00f, 0.00f, 0.00f },   // width
                { 6.85f, 6.49f, 6.68f, 7.32f, 0.00f, 0.00f, 0.00f },   // gain
                { 4.10f, 5.84f, 6.44f, 6.86f, 7.58f, 7.36f, 7.54f },   // range
            },
            { 1.087f, 1.111f, 1.245f, 1.047f, 1.144f, 1.282f, 1.194f, 1.051f, 1.131f },
            0.0531f
        },
        { // cat
            {
                { 3.04f, 5.04f, 6.03f, 6.65f, 6.86f, 7.08f, 7.35f },   // band
                { 6.66f, 7.29f, 7.69f, 0.00f, 0.00f, 0.00f, 0.00f },   // comp
                { 5.38f, 4.95f, 5.88f, 5.23f, 5.38f, 0.00f, 0.00f },   // verb
                { 3.83f, 4.34f, 4.82f, 4.39f, 3.86f, 0.00f, 0.00f },   // pan
                { 7.36f, 7.34f, 7.28f, 7.16f, 0.00f, 0.00f, 0.00f },   // delay
                { 6.44f, 7.70f, 6.40f, 7.03f, 0.00f, 0.00f, 0.00f },   // dist
                { 4.65f, 4.78f, 5.39f, 5.35f, 0.00f, 0.00f, 0.00f },   // width
                { 6.70f, 6.14f, 6.37f, 6.83f, 0.00f, 0.00f, 0.00f },   // gain
                { 2.86f, 5.44f, 5.71f, 6.79f, 7.39f, 7.22f, 7.31f },   // range
            },
            { 1.298f, 1.267f, 1.279f, 1.326f, 1.177f, 1.225f, 1.295f, 1.313f, 1.221f },
            0.0726f
        },
        { // viper
            {
                { 7.31f, 7.99f, 7.32f, 5.59f, 4.04f, 3.79f, 4.24f },   // band
                { 5.45f, 5.75f, 6.59f, 0.00f, 0.00f, 0.00f, 0.00f },   // comp
                { 4.78f, 4.96f, 5.69f, 5.76f, 5.42f, 0.00f, 0.00f },   // verb
                { 2.95f, 3.59f, 3.72f, 3.69f, 2.84f, 0.00f, 0.00f },   // pan
                { 5.87f, 6.05f, 6.42f, 7.07f, 0.00f, 0.00f, 0.00f },   // delay
                { 4.37f, 5.07f, 4.14f, 4.57f, 0.00f, 0.00f, 0.00f },   // dist
                { 3.94f, 3.50f, 4.61f, 4.25f, 0.00f, 0.00f, 0.00f },   // width
                { 5.73f, 5.15f, 5.26f, 6.08f, 0.00f, 0.00f, 0.00f },   // gain
                { 7.50f, 7.99f, 6.87f, 5.91f, 4.09f, 4.36f, 4.10f },   // range
            },
            { 1.059f, 1.031f, 1.234f, 1.030f, 1.010f, 1.051f, 0.926f, 0.880f, 1.089f },
            0.0996f
        },
        { // owl
            {
                { 2.50f, 3.04f, 4.26f, 5.68f, 6.63f, 7.30f, 6.07f },   // band
                { 6.34f, 6.91f, 7.31f, 0.00f, 0.00f, 0.00f, 0.00f },   // comp
                { 5.12f, 4.90f, 5.41f, 5.23f, 5.39f, 0.00f, 0.00f },   // verb
                { 5.73f, 6.17f, 6.83f, 6.27f, 5.54f, 0.00f, 0.00f },   // pan
                { 7.46f, 6.97f, 7.07f, 6.92f, 0.00f, 0.00f, 0.00f },   // delay
                { 5.63f, 7.25f, 5.82f, 6.48f, 0.00f, 0.00f, 0.00f },   // dist
                { 6.13f, 6.55f, 6.70f, 6.70f, 0.00f, 0.00f, 0.00f },   // width
                { 5.64f, 4.97f, 5.31f, 6.22f, 0.00f, 0.00f, 0.00f },   // gain
                { 2.50f, 2.96f, 4.30f, 5.73f, 6.74f, 6.96f, 6.09f },   // range
            },
            { 1.409f, 1.177f, 1.413f, 1.259f, 1.153f, 1.204f, 1.146f, 1.221f, 1.283f },
            0.0611f
        },
        { // bat
            {
                { 4.86f, 4.93f, 4.81f, 4.86f, 5.75f, 5.95f, 7.41f },   // band
                { 7.52f, 7.99f, 8.31f, 0.00f, 0.00f, 0.00f, 0.00f },   // comp
                { 4.45f, 4.70f, 4.62f, 4.68f, 5.03f, 0.00f, 0.00f },   // verb
                { 3.99f, 4.58f, 5.00f, 4.52f, 3.80f, 0.00f, 0.00f },   // pan
                { 8.65f, 8.36f, 8.08f, 7.83f, 0.00f, 0.00f, 0.00f },   // delay
                { 5.39f, 6.54f, 5.56f, 6.27f, 0.00f, 0.00f, 0.00f },   // dist
                { 5.40f, 5.00f, 5.61f, 5.40f, 0.00f, 0.00f, 0.00f },   // width
                { 5.11f, 4.68f, 5.06f, 5.59f, 0.00f, 0.00f, 0.00f },   // gain
                { 4.89f, 4.79f, 4.73f, 4.60f, 5.60f, 6.21f, 7.68f },   // range
            },
            { 1.455f, 1.469f, 1.399f, 1.387f, 1.317f, 1.280f, 1.249f, 1.544f, 1.551f },
            0.0991f
        },
        { // elephant
            {
                { 3.09f, 5.61f, 6.66f, 6.63f, 5.81f, 5.11f, 2.50f },   // band
                { 5.36f, 5.98f, 6.80f, 0.00f, 0.00f, 0.00f, 0.00f },   // comp
                { 5.83f, 6.16f, 7.14f, 7.07f, 6.63f, 0.00f, 0.00f },   // verb
                { 6.06f, 6.97f, 7.57f, 7.01f, 6.03f, 0.00f, 0.00f },   // pan
                { 5.49f, 6.07f, 6.26f, 6.72f, 0.00f, 0.00f, 0.00f },   // delay
                { 4.55f, 5.91f, 4.46f, 5.71f, 0.00f, 0.00f, 0.00f },   // dist
                { 6.51f, 6.99f, 7.28f, 7.00f, 0.00f, 0.00f, 0.00f },   // width
                { 6.73f, 5.90f, 6.46f, 7.20f, 0.00f, 0.00f, 0.00f },   // gain
                { 3.39f, 5.41f, 6.61f, 6.64f, 6.34f, 5.29f, 2.57f },   // range
            },
            { 0.939f, 0.949f, 0.839f, 0.931f, 0.852f, 0.953f, 0.923f, 0.850f, 1.019f },
            0.0322f
        },
    };
}
